name: Deploy ContentBased-Shop to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Cho phép chạy manual

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' # Hoặc '8.0.x' tùy theo project

    - name: Restore dependencies
      run: dotnet restore ./Shop

    - name: Build application
      run: dotnet build ./Shop --configuration Release --no-restore

    - name: Run tests (if exists)
      run: dotnet test ./Shop --no-build --verbosity normal
      continue-on-error: true # Tiếp tục nếu không có tests

    - name: Publish application
      run: dotnet publish ./Shop --configuration Release --output ./publish --no-build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'swootechsmart-g9e2gzdyd0a3gkf7'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './publish'

    - name: Deployment notification
      if: success()
      run: |
        echo "✅ Deployment successful!"
        echo "🌐 Website: https://swootechsmart-g9e2gzdyd0a3gkf7.eastasia-01.azurewebsites.net"
