name: Deploy ContentBased-Shop to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore ./Shop
    - name: Install .NET Framework 4.5 Developer Pack
      shell: powershell
      run: |
        $url = "https://download.microsoft.com/download/7/6/0/7606503A-556B-4CFA-AF6D-6F2948A1A171/NDP45-DevPack-KB2872776-x86-x64-ENU.exe"
        $installer = "$env:TEMP\ndp45devpack.exe"
        Invoke-WebRequest -Uri $url -OutFile $installer
        Start-Process -FilePath $installer -ArgumentList "/quiet", "/norestart" -Wait
        Write-Host "✅ .NET Framework 4.5 Developer Pack installed."

    - name: Build solution (Debug first)
      run: msbuild ./Shop/Shop.sln /p:Configuration=Debug /p:Platform="Any CPU"

    - name: Build solution (Release)
      run: msbuild ./Shop/Shop.sln /p:Configuration=Release /p:Platform="Any CPU"
      continue-on-error: true

    - name: Manual copy files for deployment
      shell: powershell
      run: |
        # Tạo thư mục publish
        New-Item -ItemType Directory -Path "publish" -Force
        
        # Copy files từ Debug build (fallback nếu Release failed)
        $sourcePath = "Shop/Shop"
        
        # Copy các file cần thiết
        Copy-Item "$sourcePath/*.aspx*" "publish/" -Recurse -Force -ErrorAction SilentlyContinue
        Copy-Item "$sourcePath/*.html*" "publish/" -Recurse -Force -ErrorAction SilentlyContinue  
        Copy-Item "$sourcePath/*.config" "publish/" -Force -ErrorAction SilentlyContinue
        Copy-Item "$sourcePath/bin" "publish/" -Recurse -Force -ErrorAction SilentlyContinue
        Copy-Item "$sourcePath/Content" "publish/" -Recurse -Force -ErrorAction SilentlyContinue
        Copy-Item "$sourcePath/Scripts" "publish/" -Recurse -Force -ErrorAction SilentlyContinue
        Copy-Item "$sourcePath/Views" "publish/" -Recurse -Force -ErrorAction SilentlyContinue
        Copy-Item "$sourcePath/App_Data" "publish/" -Recurse -Force -ErrorAction SilentlyContinue
        Copy-Item "$sourcePath/Global.asax*" "publish/" -Force -ErrorAction SilentlyContinue
        
        Write-Host "Files copied to publish directory"
        Get-ChildItem "publish" -Recurse | Select-Object Name, Length | Format-Table

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'swootechsmart-g9e2gzdyd0a3gkf7'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './publish'

    - name: Deployment notification
      if: success()
      run: |
        echo "✅ Deployment successful!"
        echo "🌐 Website: https://swootechsmart-g9e2gzdyd0a3gkf7.eastasia-01.azurewebsites.net"
