name: Deploy ContentBased-Shop to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Cho phép chạy manual

jobs:
  build-and-deploy:
    runs-on: windows-latest # Thay đổi sang Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore ./Shop/Shop.sln

    - name: Build application
      run: msbuild ./Shop/Shop.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Publish application
      run: msbuild ./Shop/Shop/Shop.csproj /p:Configuration=Release /p:Platform="Any CPU" /p:PublishProfile=Properties/PublishProfiles/FolderProfile.pubxml /p:PublishUrl=../publish /p:WebPublishMethod=FileSystem /p:DeployOnBuild=true

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'swootechsmart-g9e2gzdyd0a3gkf7'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './Shop/publish'

    - name: Deployment notification
      if: success()
      run: |
        echo "✅ Deployment successful!"
        echo "🌐 Website: https://swootechsmart-g9e2gzdyd0a3gkf7.eastasia-01.azurewebsites.net"
